"""empty message

Revision ID: 79ae816f422b
Revises: 81d9202f6f6d
Create Date: 2018-06-27 21:05:59.399674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ae816f422b'
down_revision = '81d9202f6f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmosphere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('light', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lightSchedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('light_id', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('stop_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_id')
    )
    op.create_table('lights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lights')
    op.drop_table('lightSchedules')
    op.drop_table('atmosphere')
    # ### end Alembic commands ###
